### ISSUE TITLE
移动端前端适配

### ISSUE THREAD

**Issue by SunXinFei** [SunXinFei/sunxinfei.github.io#13]
## 移动端px和rem
前端面对移动端常见的问题是
* 屏幕分辨率
* DPR
* 1px边框
* 2x图、雪碧图切割
rem用于随屏幕伸缩的尺寸。px用于正文文字大小、细边框等不宜随屏幕伸缩的尺寸。考虑到字体的点阵信息，一般文字尺寸多会采用 16px 20px 24px等值，若以rem指定文字尺寸，会产生诸如21px，19px这样的值，会导致字形难看，毛刺，甚至黑块，故大部分文字应该以px设置。
一般标题类文字，可能也有要求随屏幕缩放，且考虑到这类文字一般都比较大，超过30px的话，也可以用rem设置字体。
但是为了解决px字体在苹果高清屏幕上的问题，可以在css中设置不同的dpr来进行优化

**Comment by SunXinFei** [comment]
## 工具篇
查看手持端浏览器的兼容情况
![image](https://user-images.githubusercontent.com/5847281/49914191-5274c280-fecb-11e8-8aa6-eceace5b58a1.png)

**Comment by SunXinFei** [comment]
## 自定义蒙层屏蔽手持端滚动
```js
watch: {
    isShowLoading(newVal, oldVal) {
      if (newVal === true) {
        html.style.overflow = "hidden";
        html.style.height = "100%";
        body.style.overflow = "hidden";
        body.style.height = "100%";
      } else {
        html.style.overflow = "auto";
        html.style.height = "auto";
        body.style.overflow = "auto";
        body.style.height = "auto";
      }
    }
  },
forbidScroll(e) {
      e.stopPropagation();
      e.preventDefault();
    }
```
```css
.base-com-loading {
  width: 100vw;
  height: 100%;
  background: rgba(0, 0, 0, 0.6);
  position: fixed;
  z-index: 99999;
  top: 0;
  bottom: 0;
  display: flex;
  align-items: center;
  justify-content: center;
}
```
